# Generated by Django 4.1.1 on 2022-10-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = []
