# Generated by Django 4.1.1 on 2022-10-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_newDataToTable"),
    ]

    operations = []
