# Generated by Django 4.1.1 on 2022-10-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_alter_courseteachers_options_alter_lesson_options_and_more"),
    ]

    operations = []
